### ISSUE TITLE
Connecting problem

### ISSUE THREAD

**Issue by weblivepro** [hamacjumar/vscode-droidscript-code#7]
Hello,
i got DS 2.68.1
VSCode 1.89.1
DS Plugin 0.28

After put IP:port on phone i see connected device (i check version with only IP).
VSCode still sugest please connect.
In Output windows i see two times 'Disconnected'.
If i use browser i can connect and all working.

**Comment by hamacjumar** [comment]
> ## Problem
> In the "Extension Host" log:
> 
> ```
> 2024-11-08 08:42:10.563 [error] TypeError: Cannot read properties of undefined (reading 'findIndex')
> 	at WebSocket.wsOnOpen (c:\Users\owner\.vscode\extensions\droidscript.droidscript-code-0.2.8\extension.js:757:36)
> 	at WebSocket.emit (node:events:519:28)
> 	at WebSocket.setSocket (c:\Users\owner\.vscode\extensions\droidscript.droidscript-code-0.2.8\node_modules\ws\lib\websocket.js:237:10)
> 	at ClientRequest.<anonymous> (c:\Users\owner\.vscode\extensions\droidscript.droidscript-code-0.2.8\node_modules\ws\lib\websocket.js:985:15)
> 	at ClientRequest.emit (node:events:519:28)
> 	at Socket.socketOnData (node:_http_client:584:11)
> 	at Socket.emit (node:events:519:28)
> 	at addChunk (node:internal/streams/readable:559:12)
> 	at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
> 	at Readable.push (node:internal/streams/readable:390:5)
> 	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
> 2024-11-08 08:43:57.199 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:javascript'
> ```
> 
> ## Refers to extension.js
> ```
>     // get the project associated with DroidScript
>     let i = DSCONFIG.localProjects.findIndex(m => m.path == folderPath);
>     if(i >= 0) {
>         PROJECT = DSCONFIG.localProjects[i].PROJECT;
>     }
> ```
> 
> ## Work around
> 1. For new installations it may be necessary to modify the dsconfig.json file in your home folder. Fix the IP address if it shows "ip:port:undefined" to the following format. Also add the missing key for localProjects. localProjects can be empty as long as it exists.
> 2. Also, make sure you have opened a folder in the vs code work space to be associated with your app prior to trying to create/open one, for a smooth experience.
> 
> ~/dsconfig.json
> 
> ```
> {
>   "serverIP": "http://192.168.1.148:8088",
>   "localProjects": []
> }
> ```

Thank you for looking into this. Highly appreciated.

**Comment by tutosrive** [comment]
Ya lo hice, funciona aún en 2025... (Pero, si es un problema tan mínimo, porque no lo han arreglado?)

**Comment by TonyGravagno** [comment]
See [my fork/branch](https://github.com/TonyGravagno/vscode-droidscript-code/tree/tg-0.3.5-01) where the connection is working.
See the v0.3.5.md file there for documentation about what that fork is.  
See the contributing.md file there for how to load and test the extension.

This is not official. Discussion started in Discord [here](https://discord.com/channels/985908716060684388/1412910278693093427).

**Comment by TonyGravagno** [comment]
In 0.3.6 this area of comms has a significant update that addresses all of this and more.

This is advance notice to those of you who read these comments. 0.3.6 will be available soon.

**Comment by TonyGravagno** [comment]
I recommend closing this issue on the old v0.28 (0.2.8) release as Fixed.
The issue was fixed in 0.3.4 and has not re-appeared in production 0.3.5 or the 0.3.6 beta.
